services:

  web:
    build: .
    env_file: .env
    command: gunicorn --workers 3 --bind 0.0.0.0:8003 --timeout 500 life.wsgi:application
    volumes:
      - ./:/app
    expose:
      - 8003
    restart: unless-stopped
    network_mode: host
