# Generated by Django 5.0.3 on 2024-04-06 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_notes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notes",
            options={"verbose_name_plural": "Notes"},
        ),
        migrations.RenameField(
            model_name="notes",
            old_name="notes",
            new_name="my_notes",
        ),
    ]
