# Generated by Django 5.0.3 on 2024-04-06 20:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_notes_options_rename_notes_notes_my_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="my_notes",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
