# Generated by Django 5.0.3 on 2024-04-06 20:30

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_notes_my_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="my_notes",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
