# Generated by Django 5.1.4 on 2025-01-16 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Exercício')),
                ('video_url', models.URLField(blank=True, verbose_name='URL do Vídeo')),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da série')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Série do usuário',
                'verbose_name_plural': 'Séries do usuário',
            },
        ),
        migrations.CreateModel(
            name='SeriesExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('stretching', 'Alongamento'), ('mobility', 'Mobilidade'), ('activation', 'Ativação'), ('motor_control', 'Controle Motor'), ('warm_up', 'Aquecimento'), ('strength', 'Força')], default='strength', max_length=100, verbose_name='Grupo')),
                ('order', models.PositiveIntegerField(verbose_name='Ordem')),
                ('color', models.CharField(blank=True, choices=[('#FFCCCC', 'Vermelho'), ('#CCFFCC', 'Verde'), ('#CCCCFF', 'Azul'), ('#FFFFCC', 'Amarelo'), ('#E5CCFF', 'Roxo'), ('#FFCCE5', 'Rosa')], max_length=10, null=True, verbose_name='Cor')),
                ('sets', models.PositiveIntegerField(verbose_name='Sets')),
                ('repetitions_or_time', models.PositiveIntegerField(verbose_name='Qtd. (Repetições ou Tempo)')),
                ('unit', models.CharField(choices=[('repetitions', 'Repetições'), ('seconds', 'Segundos')], default='repetitions', max_length=15, verbose_name='Unidade')),
                ('load', models.PositiveIntegerField(blank=True, null=True, verbose_name='Carga (Kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.exercise', verbose_name='Exercício')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.series', verbose_name='Série')),
            ],
            options={
                'verbose_name': 'Exercício da Série',
                'verbose_name_plural': 'Exercícios da Série',
            },
        ),
    ]
