# Generated by Django 5.1.4 on 2025-02-03 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriesexercise',
            name='series',
        ),
        migrations.RemoveField(
            model_name='seriesexercise',
            name='exercise',
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do programa')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Programa do usuário',
                'verbose_name_plural': 'Programas do usuário',
            },
        ),
        migrations.CreateModel(
            name='ProgramExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('stretching', 'Alongamento'), ('mobility', 'Mobilidade'), ('activation', 'Ativação'), ('motor_control', 'Controle Motor'), ('warm_up', 'Aquecimento'), ('strength', 'Força')], default='strength', max_length=100, verbose_name='Grupo')),
                ('order', models.PositiveIntegerField(verbose_name='Ordem')),
                ('color', models.CharField(blank=True, choices=[('#FFCCCC', 'Vermelho'), ('#CCFFCC', 'Verde'), ('#CCCCFF', 'Azul'), ('#FFFFCC', 'Amarelo'), ('#E5CCFF', 'Roxo'), ('#FFCCE5', 'Rosa')], max_length=10, null=True, verbose_name='Cor')),
                ('sets', models.PositiveIntegerField(verbose_name='Série')),
                ('repetitions_or_time', models.PositiveIntegerField(verbose_name='Qtd. (Repetições ou Tempo)')),
                ('unit', models.CharField(choices=[('repetitions', 'Repetições'), ('seconds', 'Segundos')], default='repetitions', max_length=15, verbose_name='Unidade')),
                ('load', models.PositiveIntegerField(blank=True, null=True, verbose_name='Carga (Kg)')),
                ('observation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.exercise', verbose_name='Exercício')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.trainingprogram', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Exercício do programa',
                'verbose_name_plural': 'Exercícios do programa',
            },
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.DeleteModel(
            name='SeriesExercise',
        ),
    ]
