# Generated by Django 5.1.5 on 2025-02-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_remove_seriesexercise_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programexercise',
            name='group',
            field=models.CharField(choices=[('release', 'Liberação'), ('stretching', 'Alongamento'), ('mobility', 'Mobilidade'), ('motor_control', 'Controle Motor'), ('stability', 'Estabilidade'), ('power', 'Potência'), ('strength', 'Força')], default='strength', max_length=100, verbose_name='Grupo'),
        ),
    ]
