# Generated by Django 5.1.5 on 2025-02-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_programexercise_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programexercise',
            name='load',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Carga (Kg)'),
        ),
    ]
