# Generated by Django 5.1.15 on 2026-04-06 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_alter_programexercise_load'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'Exercise', 'verbose_name_plural': 'Exercises'},
        ),
        migrations.AlterModelOptions(
            name='programexercise',
            options={'verbose_name': 'Programme exercise', 'verbose_name_plural': 'Programme exercises'},
        ),
        migrations.AlterModelOptions(
            name='trainingprogram',
            options={'verbose_name': 'User programme', 'verbose_name_plural': 'User programmes'},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Exercise name'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='color',
            field=models.CharField(blank=True, choices=[('#FFCCCC', 'Red'), ('#CCFFCC', 'Green'), ('#CCCCFF', 'Blue'), ('#FFFFCC', 'Yellow'), ('#E5CCFF', 'Purple'), ('#FFCCE5', 'Pink')], max_length=10, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.exercise', verbose_name='Exercise'),
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='group',
            field=models.CharField(choices=[('release', 'Release'), ('stretching', 'Stretching'), ('mobility', 'Mobility'), ('motor_control', 'Motor Control'), ('stability', 'Stability'), ('power', 'Power'), ('strength', 'Strength')], default='strength', max_length=100, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='load',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Load (Kg)'),
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='observation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.trainingprogram', verbose_name='Programme'),
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='repetitions_or_time',
            field=models.PositiveIntegerField(verbose_name='Qty. (Reps or Time)'),
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='sets',
            field=models.PositiveIntegerField(verbose_name='Sets'),
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='unit',
            field=models.CharField(choices=[('repetitions', 'Repetitions'), ('seconds', 'Seconds')], default='repetitions', max_length=15, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Programme name'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
